Attempt adding a build product pushing to the generic package reg

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -1,5 +1,7 @@
 stages:
   - test
+  - build
+  - publish
 
 # Global default parameters set for all jobs unless overridden by job-specific
 # configuration.
@@ -13,43 +15,55 @@ variables:
   LC_ALL: "C.UTF-8"
   LANG: "C.UTF-8"
 
-# Common job specification not otherwise specifiable in the `default` section
-# above.
+
+###############################################################################
+# Run Conditions
+#
+
+# Run rules to activate at the major junction points: merge requests, tag
+# pipelines and branch pipelines for masters.
+.run_automatically:
+  rules:
+    - if: $CI_MERGE_REQUEST_IID
+      when: on_success
+    - if: $CI_COMMIT_TAG
+      when: on_success
+    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
+      when: on_success
+    - when: never  # explicit fail-exclude terminal condition.
+
+# Rules for running
+# TODO: When moving to enforcing forky workflow, this will not be necessary.
+.run_on_masters:
+  rules:
+    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
+      when: on_success
+    - when: never
+
+
+###############################################################################
+# Jobs -- Testing
+
 .test_job_defaults:
+  extends:
+    - .run_automatically
   stage: test
   tags:
     - linux
     - docker
     - test
-  rules:
-    # Enable tests when running:
-    #   - a merge-request pipeline.
-    #   - tag builds
-    #   - branch pipelines when the branch pipeline is for the default branch
-    - if: $CI_MERGE_REQUEST_IID
-    - if: $CI_COMMIT_TAG
-    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
-    - when: never  # explicit fail-exclude terminal condition.
-
-# Common setup script lines for test jobs
-.test_setup: &test_setup
-  - apt-get -y update
-  - python --version
-  - pip install -U pip
-  - pip install -r requirements.txt
-                -e .
+  before_script:
+    - python --version
+    - pip install -U pip
+    - pip install -r requirements.txt
+                  -e .
 
 .pytest_cmd: &pytest_cmd
   - pytest --cov=smqtk_dataprovider --cov-config=.pytest.coveragerc
 
-
-###############################################################################
-# Jobs
-
 test:docs_build:
   extends: .test_job_defaults
   script:
-    - *test_setup  # expand `&test_setup` anchor above into here.
     - cd docs
     - make html
     - stat _build/html/index.html
@@ -68,7 +82,6 @@ test:unittests:
                   "opt-mimetype-magic.txt"]
   image: $IMAGE
   script:
-    - *test_setup  # expand `&test_setup` anchor above into here.
     - |
       REQ_FILE="requirements/$OPT_REQ"
       if [[ -f "$REQ_FILE" ]]
@@ -80,11 +93,66 @@ test:unittests:
 test:lint:
   extends: .test_job_defaults
   script:
-    - *test_setup  # expand `&test_setup` anchor above into here.
     - flake8
 
 test:typecheck:
   extends: .test_job_defaults
   script:
-    - *test_setup
     - mypy
+
+
+###############################################################################
+# Jobs -- Builds
+
+.build_job_defaults:
+  stage: build
+  tags:
+    - linux
+    - docker
+    - build
+
+build:build_wheel:
+  extends:
+    - .build_job_defaults
+    - .run_automatically
+  script:
+    - python setup.py bdist_wheel
+  artifacts:
+    paths:
+      - dist/*.whl
+    when: on_success
+
+
+###############################################################################
+# Jobs -- Publishing
+
+.publish_job_defaults:
+  stage: publish
+  tags:
+    - linux
+    - docker
+    - build
+
+publish:generic_latest_wheel:
+  # This job is an intermediate workaround to package sharing before moving to
+  # github / PYPI.
+  extends:
+    - .publish_job_defaults
+    - .run_on_masters
+  stage: publish
+  dependencies:
+    - build:build_wheel
+  script:
+    - ARCH_NAME="smqtk-dataprovider-latest.tgz"
+    - DIST_FILES=($(ls dist))
+    - |
+      if [[ "${#DIST_FILES[@]}" -ne 1 ]]
+      then
+        echo "ERROR: More than one dist file detected:"
+        ls -lhF dist
+        exit 1
+      fi
+    - tar czf "$ARCH_NAME" -C dist "${DIST_FILES[0]}"
+    - >
+      curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file "$ARCH_NAME"
+      "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/latest_wheel/0.0.0/$ARCH_NAME"
